### ISSUE TITLE
Android13没有这个 权限啦 Manifest.permission.WRITE_EXTERNAL_STORAGE

### ISSUE THREAD

**Issue by moshangpiaoxue** [ZS-ZhangsShun/EasyImageCompressor#3]

**Comment by ZS-ZhangsShun** [comment]
多谢提醒，Android 13 大家按照官方的权限分类和各自具体情况来处理吧

**Comment by moshangpiaoxue** [comment]
大佬，EasyImgCompress类141行的权限判断 更新去掉或者加个版本判断呗

**Comment by ZS-ZhangsShun** [comment]
感谢提醒，预计今晚可以加上并发布新版本出来

1、6.0及以上并且android 13以下版本需要在代码中动态申请Manifest.permission.WRITE_EXTERNAL_STORAGE 可以参考示例代码
2、Android 13 大家按照官方的权限分类和各自具体情况来处理，比如使用 Manifest.permission.READ_MEDIA_IMAGES权限

**Comment by ZS-ZhangsShun** [comment]
版本已经更新，使用1.0.11及以上版本即可
