### ISSUE TITLE
MultiPicsBuilder.cacheDir() is useless 

### ISSUE THREAD

**Issue by chensimin920511** [ZS-ZhangsShun/EasyImageCompressor#4]
public MultiPicsBuilder cacheDir(String autoReconnect) {
            this.cacheDir = cacheDir;
            return this;
        }

**Comment by ZS-ZhangsShun** [comment]
tks, i will repair it tonight

**Comment by ZS-ZhangsShun** [comment]
please update to 1.0.15 or higher version
