### ISSUE TITLE
The compressed image will be partially cropped

### ISSUE THREAD

**Issue by chensimin920511** [ZS-ZhangsShun/EasyImageCompressor#5]
The compressed image will be partially cropped

**Comment by ZS-ZhangsShun** [comment]
> The compressed image will be partially cropped

first,please provide the compression parameters you passed in
second,please provide me with your picture
third,please upload the cut image

My email is 18763552493@163.com

**Comment by ZS-ZhangsShun** [comment]
> The compressed image will be partially cropped

版本升级到1.1.5就可以了
在此版本中，将Matrix压缩添加到开关控制中，默认不开启
可通过 enableMatrixCompress(true)来开启 实现对尺寸的精确缩放，不过开启后有可能出现图片边缘被裁剪
